anguage: node_js

node_js: stable

cache:
    apt: true
    directories:
        - node_modules

before_install:
    - export TZ='Asia/Shanghai'
    - npm install hexo-cli -g
    - chmod +x ./publish-to-gh-pages.sh

install:
    - npm install

before_script:
    - npm install -g gulp
    - npm install -g gulp-debug
    - npm install -g gulp-clean-css
    - npm install -g gulp-uglify
    - npm install -g gulp-htmlmin
    - npm install -g gulp-htmlclean
    - npm install -g gulp-imagemin
    - npm install -g gulp-changed
    - npm install -g gulp-if
    - npm install -g gulp-plumber
    - npm install -g run-sequence
    - npm install -g del

script:
    - hexo clean
    - hexo g
    - gulp

after_script:
    - ./publish-to-gh-pages.sh

branches:
    only:
        - hexo

env:
    global:
        - GH_REF: github.com/wxiguo/wxiguo.github.io.git